apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app.kubernetes.io/name: echo-server
spec:
  imagePullSecrets:
    - name: gitlab-registry
  containers:
    - name: echo-server
      image: registry.gitlab.com/metadata1/app-platform/notification-service:echo-server
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: http
      env:
        - name: PORT
          value: "8080"
        - name: FILE_NAME
          value: "/data/echo-server.csv"
      volumeMounts:
        - mountPath: "/data"
          name: echo-server-storage
  volumes:
    - name: echo-server-storage
      persistentVolumeClaim:
        claimName: echo-server-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: echo-server
spec:
  selector:
    app.kubernetes.io/name: echo-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
